spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/task_manager?serverTimezone=UTC
    username: gisung
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6380

jwt:
  secretKey: gisung-project-taskmanagersystem-jwt-secret-key
  access:
    expiration: 3600000

  refresh:
    expiration: 604800000

kafka:
  bootstrap-server:
    - localhost:10000
    - localhost:10001
    - localhost:10002